# name = input()
# number = int(input())
# group = str(number // 100)
# list = str(number % 10)
# bed = str(number // 10 - number // 100 * 10)

# print("Группа №" + group)
# print(list + ". " + name)
# print("Шкафчик: " + str(number) + ".")
# print("Кроватка: " + bed + ".")

name = input()
number = int(input())
print(f"Группа №{number // 100}.")
print(f"{number % 10}. {name}.")
print(f"Шкафчик: {number}.")
print(f"Кроватка: {number // 10 - number // 100 * 10}.")